# Generated by Django 5.0.6 on 2024-06-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadwayTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter teacher's name", max_length=255)),
                ('subject', models.CharField(help_text='Enter the subject', max_length=255)),
                ('teacher_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
