# Generated by Django 5.0.6 on 2024-06-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_broadwayteacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BroadwayTeacher',
        ),
    ]
