# Generated by Django 5.0.6 on 2024-06-18 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_delete_broadwayteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Class name')),
                ('section', models.CharField(max_length=40, verbose_name='lab room / section')),
                ('status', models.BooleanField(default=False)),
                ('class_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='class type')),
                ('class_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='broadwaystudent',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentclass'),
        ),
    ]
