# Generated by Django 5.0.6 on 2024-06-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studentclass_created_date_studentclass_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='started_date',
        ),
    ]
