# Generated by Django 5.0.6 on 2024-06-19 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentclass_created_date_studentclass_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadwayTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='student name', max_length=255, null=True)),
                ('address', models.CharField(max_length=33)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentclass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.broadwayteacher'),
        ),
    ]
